### ISSUE TITLE
Missing slides

### ISSUE THREAD

**Issue by mewmew** [gophercon/2014-talks#21]
Hi.

I love the initiative to create a repository containing all the slides from the GopherCon. It is much appreciated for us fellow Gophers who were unable to participate.

As of currently there are a few talks missing from the list. I'll list them below in the hopes that they can be added to the repository.
- Alan Shreve - Build Your Developer Tools in Go
- David Symonds - Gophers on a Plane: The Story of Go on App Engine
- Gustavo Niemeyer, Steve Francia - Painless Data Storage with MongoDB and Go
- Kelsey Falter - From Node.js to Go
- Mike Gehard - Taking Back the Command Line with Go

Cheers /u

**Comment by dgryski** [comment]
The gobot.io teams didn't really have slides, just demos.

Petar's slides are in the repo already.

**Comment by dgryski** [comment]
Blake's talk was replaced with a panel discussion with the Go team. No slides.

**Comment by dgryski** [comment]
The "writing a multiplayer game" slides are in the repo as "killer robots are a concurrency problem"

**Comment by mewmew** [comment]
Thanks for the quick response. I've added links to those slides in the readme and updated the issue with regards to the information you provided.

**Comment by muloka** [comment]
Any word about @Kfalter's slides From Node.js to Go?

**Comment by cnbuff410** [comment]
@muloka Just FYI the video is already out(http://confreaks.com/videos/3428-gophercon2014-from-node-js-to-go) and looks like the slides is just a couple of pages.

**Comment by muloka** [comment]
I actually watched the video and she keeps referring to a diagram on her slide though the video doesn't show that actual slide.

**Comment by mewmew** [comment]
The slides of GopherCon 2014 are either in place by now, or have been lost to the ages. Thanks to everyone who contributed to make GopherCon 2014 happen! Closing this issue for now.
